name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: CGO_ENABLED=0 go test ./... -cover
